//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _201817380227易炽昆.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int AdminID { get; set; }
        public string AdminLogin { get; set; }
        public string AdminPwd { get; set; }
        public string AdminName { get; set; }
        public string AdminIdentity { get; set; }
        public string AdminSex { get; set; }
        public int AdminAge { get; set; }
        public string AdminPhone { get; set; }
        public string State { get; set; }
    }
}
