//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _201817380227易炽昆.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeDBEntities : DbContext
    {
        public HomeDBEntities()
            : base("name=HomeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<BuyHouse> BuyHouse { get; set; }
        public virtual DbSet<Lease> Lease { get; set; }
        public virtual DbSet<LeaseHouse> LeaseHouse { get; set; }
        public virtual DbSet<Picture> Picture { get; set; }
        public virtual DbSet<RequestRent> RequestRent { get; set; }
        public virtual DbSet<SellHouse> SellHouse { get; set; }
        public virtual DbSet<StagesBuyHouse> StagesBuyHouse { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
