//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _201817380227易炽昆.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaseHouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeaseHouse()
        {
            this.Lease = new HashSet<Lease>();
            this.Picture = new HashSet<Picture>();
        }
    
        public int LeaseID { get; set; }
        public string Position { get; set; }
        public string Describe { get; set; }
        public double Area { get; set; }
        public string HouseType { get; set; }
        public decimal Price { get; set; }
        public string LeaseFurniture { get; set; }
        public string IsLease { get; set; }
        public string Contacts { get; set; }
        public string ContactsPhone { get; set; }
        public int LeaseType { get; set; }
        public string HousePhone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lease> Lease { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Picture { get; set; }
    }
}
