//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _201817380227易炽昆.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lease
    {
        public int ID { get; set; }
        public System.DateTime Time { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int UserID { get; set; }
        public int LeaseID { get; set; }
        public int AdminID { get; set; }
        public Nullable<int> RentingState { get; set; }
    
        public virtual LeaseHouse LeaseHouse { get; set; }
        public virtual User User { get; set; }
    }
}
