//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _201817380227易炽昆.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellHouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SellHouse()
        {
            this.BuyHouse = new HashSet<BuyHouse>();
            this.Picture = new HashSet<Picture>();
            this.StagesBuyHouse = new HashSet<StagesBuyHouse>();
        }
    
        public int SellID { get; set; }
        public string Position { get; set; }
        public decimal SellPrice { get; set; }
        public string Describe { get; set; }
        public double Area { get; set; }
        public string HouseType { get; set; }
        public string IsSell { get; set; }
        public string Contacts { get; set; }
        public string ContactsPhone { get; set; }
        public Nullable<int> BuyType { get; set; }
        public string HousePhone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyHouse> BuyHouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Picture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StagesBuyHouse> StagesBuyHouse { get; set; }
    }
}
