//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _201817380227易炽昆.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagesBuyHouse
    {
        public int ID { get; set; }
        public System.DateTime Time { get; set; }
        public string IsFinish { get; set; }
        public int UserID { get; set; }
        public int SellID { get; set; }
        public int AdminID { get; set; }
        public Nullable<int> State { get; set; }
        public int NowStages { get; set; }
        public int ByStages { get; set; }
    
        public virtual SellHouse SellHouse { get; set; }
        public virtual User User { get; set; }
        public virtual Admin Admin { get; set; }
    }
}
